GlobalPlanner:
        allow_unknown: false
        default_tolerance: 0.1
        visualize_potential: false
        use_dijkstra: true
        use_quadratic: true
        use_grid_path: false
        old_navfn_behavior: false
