
local_costmap:
    #Coordinate frame and tf parameters
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 3.0

    #Rate parameters
    update_frequency: 5.0
    publish_frequency: 1.0

    #map params
    static_map: false
    rolling_window: true
    width: 4.0
    height: 4.0
    resolution: 0.05

    #robot model
    inscribed_radius: 0.22
    circumscribed_radius: 0.25

    plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: local_inflation_layer,  type: "costmap_2d::InflationLayer"}
