base_global_planner: "global_planner/GlobalPlanner"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

controller_frequency: 4.0
planner_patience: 10.0
controller_patience: 4.0
conservative_reset_dist: 0.5
recovery_behavior_enabled: true
clearing_rotation_allowed: false
shutdown_costmaps: false
oscillation_timeout: 10.0
oscillation_distance: 0.3
planner_frequency: 1.0
max_planning_retries: -1.0
